### PR TITLE
Missing simulator JS and CSS

### PR DESCRIPTION
**Pull request by miguelalba**

### CODE REVIEW

**Review by schuelet — COMMENTED** [review]
jssimulator.css is binary and unusable

**Review by schuelet — CHANGES_REQUESTED** [review]
why do we still have the jssimulator.js file if yesterday we spent hours rewriting that code into the .ftl file´?

**Comment by miguelalba** [comment]
> why do we still have the jssimulator.js file if yesterday we spent hours rewriting that code into the .ftl file´?

(index):1164 Uncaught (in promise) ReferenceError: submitSimulation is not defined
    at buildSimulatorWindow ((index):1164)

**Comment by miguelalba** [comment]
> jssimulator.css is binary and unusable

It had wrong encoding. It is fixed. Please test again.

**Review by schuelet — APPROVED** [review]

**Pull request merged**
